# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'C:\digiage\platforms\ios\DIGIAGE' do
	project 'C:\digiage\platforms\ios\DIGIAGE.xcodeproj'
	pod 'FirebaseMessaging', '~> 2.0.0'
end
